version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - test:
# ...
  - restore_cache:
      keys:
      - v1-dep-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - v1-dep-{{ .Branch }}-
      - v1-dep-
    - run:
        name: update bundler
        command: |
          gem update --system
          gem install bundler
    - run:
        name: install gem dependencies
        command: |
          bundle config set clean 'true'
          bundle config set path 'vendor/bundle'
          bundle install --jobs=4 --retry=3
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle
